1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

--> **Purpose of NumPy in Scientific Computing and Data Analysis**
NumPy (Numerical Python) is a fundamental library for numerical computing in Python. It provides a high-performance, multidimensional array object and a collection of mathematical functions designed for efficient operations on large datasets.

NumPy is widely used in:
- **Scientific computing**: Performing mathematical and statistical computations.
- **Data analysis**: Handling large datasets efficiently.
- **Machine learning and AI**: Serving as a foundation for libraries like TensorFlow, scikit-learn, and Pandas.
- **Engineering and simulations**: Conducting numerical modeling and simulations.


### **Advantages of NumPy**
1. **Efficient Array Operations**  
   - NumPy provides the `ndarray` object, which is more memory-efficient and faster than Python's built-in lists.
   - Supports vectorized operations, eliminating the need for slow Python loops.

2. **Performance Improvement**  
   - NumPy operations are implemented in C and optimized for performance.
   - Uses contiguous memory storage, improving cache performance.
   - Supports parallel processing via libraries like BLAS and LAPACK.

3. **Broad Functionality**  
   - Offers a wide range of mathematical, statistical, and linear algebra functions.
   - Supports Fast Fourier Transforms (FFT), random number generation, and integration with other scientific libraries.

4. **Interoperability**  
   - Works seamlessly with Pandas, SciPy, Matplotlib, and machine learning frameworks like TensorFlow and PyTorch.
   - Can interface with C/C++ and Fortran, allowing high-performance computing.

5. **Broadcasting and Advanced Indexing**  
   - Supports broadcasting, allowing operations on arrays of different shapes without explicit looping.
   - Provides advanced indexing, making data manipulation easier.

6. **Ease of Use**  
   - Syntax is simple and concise compared to traditional loops and list-based operations.
   - Reduces code complexity while improving readability.


 **How NumPy Enhances Python’s Numerical Capabilities**
- **Replaces Python lists**: NumPy arrays (`ndarrays`) are more efficient in terms of memory and speed.
- **Enables vectorization**: Operations are applied element-wise without explicit loops.
- **Optimized mathematical computations**: Linear algebra, statistical functions, and random number generation are faster.
- **Facilitates large-scale data handling**: NumPy is designed to handle multi-dimensional arrays efficiently.

Overall, NumPy significantly enhances Python’s capabilities for numerical computing and is essential for scientific and data-driven applications.

 2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

-->np.mean() vs np.average() in NumPy
np.mean()
Purpose: Calculates the arithmetic mean (average) along the specified axis.

Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)

Parameters:

a: Input array.

axis: Axis along which the means are computed. By default, the mean is computed for the flattened array.

dtype: Type to use in computing the mean.

out: Alternative output array to place the result.

keepdims: If True, the reduced axes are left as dimensions with size one.

np.average()
Purpose: Calculates the weighted average along the specified axis. If no weights are provided, it behaves like np.mean().

Syntax: np.average(a, axis=None, weights=None, returned=False)

Parameters:

a: Input array.

axis: Axis along which the averages are computed.

weights: An array of weights associated with the values in a. If None, the function calculates the mean.

returned: If True, returns a tuple of the average and the sum of the weights.

Key Differences:
Weighted Average:

np.mean(): Always calculates the simple arithmetic mean.

np.average(): Can calculate a weighted average if weights are provided.

Behavior Without Weights:

np.mean(): Only calculates the simple mean.

np.average(): Behaves like np.mean() when no weights are provided.

Return Value:

np.mean(): Returns the mean.

np.average(): Can return a tuple of the average and the sum of the weights if returned=True.

When to Use Each:
Use np.mean() when you need to calculate the simple arithmetic mean and do not require weighting.

Use np.average() when you need to calculate a weighted average or if there's a possibility you might need to include weights in the future.

3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

-->Reversing a NumPy array can be achieved using various methods depending on the array's dimensions and the axes you want to reverse along. Let's explore some of these methods with examples for 1D and 2D arrays:

### 1. Reversing a 1D Array
To reverse a 1D array, you can use slicing.

#### Example:
```python
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Reverse the array using slicing
reversed_arr = arr[::-1]

print("Original array:", arr)
print("Reversed array:", reversed_arr)
```

### Output:
```plaintext
Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]
```

### 2. Reversing a 2D Array
For a 2D array, you can reverse along different axes using slicing. You can reverse along rows, columns, or both.

#### Example 1: Reverse Rows
```python
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse the rows
reversed_rows = arr[::-1, :]

print("Original array:\n", arr)
print("Reversed rows:\n", reversed_rows)
```

### Output:
```plaintext
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
```

#### Example 2: Reverse Columns
```python
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse the columns
reversed_columns = arr[:, ::-1]

print("Original array:\n", arr)
print("Reversed columns:\n", reversed_columns)
```

### Output:
```plaintext
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
```

#### Example 3: Reverse Both Rows and Columns
```python
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse both rows and columns
reversed_both = arr[::-1, ::-1]

print("Original array:\n", arr)
print("Reversed both rows and columns:\n", reversed_both)
```

### Output:
```plaintext
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed both rows and columns:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
```

### Summary:
- **1D Array**: Use slicing `[::-1]` to reverse the array.
- **2D Array**:
  - Reverse rows: Use slicing `[::-1, :]`.
  - Reverse columns: Use slicing `[:, ::-1]`.
  - Reverse both rows and columns: Use slicing `[::-1, ::-1]`.

These methods allow you to easily reverse the elements in NumPy arrays along different axes.

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

-->### **Determining the Data Type of Elements in a NumPy Array**
In NumPy, you can determine the data type of elements in an array using the `.dtype` attribute:

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int32 or int64 (depending on system)
```
For more detailed information, you can use:

```python
print(type(arr[0]))  # Checks the type of an individual element
```

You can also check and specify data types explicitly when creating arrays:

```python
arr_float = np.array([1, 2, 3], dtype=np.float32)
print(arr_float.dtype)  # Output: float32
```

---

## **Importance of Data Types in Memory Management and Performance**
1. **Memory Efficiency**  
   - NumPy allows selecting data types (`int8`, `int16`, `int32`, `int64`, `float32`, etc.), optimizing memory usage.
   - Example: `int8` (1 byte) vs. `int64` (8 bytes) – choosing the appropriate type saves memory.

2. **Performance Optimization**  
   - Smaller data types improve performance by reducing memory footprint and improving cache efficiency.
   - Vectorized operations on `float32` arrays are often faster than on `float64` due to lower precision requirements.

3. **Avoiding Unexpected Behavior**  
   - Operations on mixed data types can lead to **type promotion**, increasing memory usage.
   - Example:
     ```python
     arr = np.array([1, 2, 3], dtype=np.int8) + 300
     print(arr.dtype)  # May convert to int16 to prevent overflow
     ```

4. **Compatibility with External Libraries**  
   - Ensures correct data representation when interacting with machine learning frameworks (e.g., TensorFlow prefers `float32` for efficiency).

---

 ## **Best Practices**
- Use `float32` instead of `float64` for deep learning to save memory.
- Use `int8` or `uint8` for image processing where possible.
- Convert data types only when necessary to avoid **precision loss** and **unnecessary conversions**.

Choosing the right NumPy data type enhances performance, reduces memory overhead, and prevents errors in numerical computations.

5.. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

-->NumPy ndarrays
ndarray stands for "N-dimensional array" in NumPy. It is the primary data structure used in the NumPy library and provides a powerful way to work with large, multi-dimensional arrays and matrices of numerical data.

Key Features of ndarrays:
N-Dimensional:

Supports multi-dimensional arrays, allowing for the creation of arrays with any number of dimensions.

Flexible and can handle scalar (0-D), vector (1-D), matrix (2-D), and higher-dimensional arrays.

Homogeneous Data Type:

All elements in an ndarray must be of the same data type.

This ensures efficient memory usage and fast computation.

Element-wise Operations:

Supports efficient element-wise operations and broadcasting.

Allows for vectorized operations, eliminating the need for explicit loops.

Memory Efficiency:

Uses contiguous blocks of memory, which makes access and manipulation of data faster.

Significantly more memory-efficient than Python lists, especially for large datasets.

Powerful Mathematical Functions:

Provides a wide range of mathematical and statistical functions that operate on ndarrays.

Functions include trigonometric, statistical, linear algebra, and random number operations.

Advanced Indexing and Slicing:

Supports advanced indexing and slicing, making it easy to manipulate data.

Allows for operations on subsets of data without copying the data.

Differences from Standard Python Lists:
Data Type:

NumPy ndarrays: Homogeneous (all elements are of the same type).

Python lists: Heterogeneous (can contain elements of different types).

Performance:

NumPy ndarrays: Highly optimized for numerical operations, leading to faster computations.

Python lists: Slower for numerical operations due to lack of optimization and type flexibility.

Memory Usage:

NumPy ndarrays: More memory-efficient due to homogeneous data type and contiguous memory storage.

Python lists: Less memory-efficient because elements can be of different types and are stored as individual objects.

Functionality:

NumPy ndarrays: Includes powerful mathematical, statistical, and linear algebra functions.

Python lists: Basic functionalities for data manipulation without built-in advanced mathematical functions.

Indexing and Slicing:

NumPy ndarrays: Supports advanced and multi-dimensional slicing and indexing.

Python lists: Basic slicing and indexing, limited to 1-D and basic 2-D operations.

In [10]:
#NUMPY NDARRAY
import numpy as np

# Create a 2D ndarray
nd_array = np.array([[1, 2, 3], [4, 5, 6]])

# Element-wise operations
squared_nd_array = nd_array ** 2
sum_nd_array = np.sum(nd_array, axis=0)

print("NumPy ndarray:\n", nd_array)
print("Squared ndarray:\n", squared_nd_array)
print("Sum along columns:\n", sum_nd_array)


NumPy ndarray:
 [[1 2 3]
 [4 5 6]]
Squared ndarray:
 [[ 1  4  9]
 [16 25 36]]
Sum along columns:
 [5 7 9]


In [11]:
#PYTHON LIST
# Create a 2D list
py_list = [[1, 2, 3], [4, 5, 6]]

# Manually perform element-wise operations
squared_py_list = [[x**2 for x in row] for row in py_list]
sum_py_list = [sum(col) for col in zip(*py_list)]

print("Python list:\n", py_list)
print("Squared list:\n", squared_py_list)
print("Sum along columns:\n", sum_py_list)


Python list:
 [[1, 2, 3], [4, 5, 6]]
Squared list:
 [[1, 4, 9], [16, 25, 36]]
Sum along columns:
 [5, 7, 9]


6.. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

-->Performance Benefits of NumPy Arrays over Python Lists
When dealing with large-scale numerical operations, NumPy arrays offer significant performance advantages over standard Python lists. Let's break down the key benefits:

Memory Efficiency:

NumPy Arrays: Use contiguous blocks of memory, which reduces the overhead and leads to more efficient memory usage.

Python Lists: Each element in a Python list is an object with additional memory overhead.


In [12]:
import numpy as np
import sys

# Create a large NumPy array
numpy_array = np.arange(1000000)
numpy_memory = numpy_array.nbytes

# Create a large Python list
python_list = list(range(1000000))
python_memory = sys.getsizeof(python_list) + sum(sys.getsizeof(item) for item in python_list)

print(f"NumPy array memory: {numpy_memory} bytes")
print(f"Python list memory: {python_memory} bytes")


NumPy array memory: 8000000 bytes
Python list memory: 36000056 bytes


Performance and Speed:

NumPy Arrays: Operations are implemented in C and optimized for performance. Supports vectorized operations, allowing element-wise operations without explicit loops.

Python Lists: Operations are less optimized and often require explicit loops, leading to slower performance.

In [14]:
import numpy as np
import time

# Create large arrays/lists
numpy_array = np.arange(1000000)
python_list = list(range(1000000))

# Measure time for NumPy array operations
start_time = time.time()
numpy_result = numpy_array * 2
numpy_time = time.time() - start_time

# Measure time for Python list operations
start_time = time.time()
python_result = [x * 2 for x in python_list]
python_time = time.time() - start_time

print(f"NumPy operation time: {numpy_time} seconds")
print(f"Python list operation time: {python_time} seconds")


NumPy operation time: 0.011659622192382812 seconds
Python list operation time: 0.11707234382629395 seconds


Vectorized Operations:

NumPy Arrays: Support vectorized operations, which allows for efficient element-wise operations on entire arrays without the need for explicit loops.

Python Lists: Requires explicit loops for element-wise operations, which can be less readable and slower.

In [15]:
import numpy as np

# Create a large NumPy array
numpy_array = np.arange(1000000)

# Vectorized operation (element-wise multiplication)
numpy_result = numpy_array * 2


Advanced Mathematical Functions:

NumPy Arrays: Provide a wide range of mathematical and statistical functions that are highly optimized.

Python Lists: Lack built-in advanced mathematical functions, often requiring the use of loops or external libraries.

In [16]:
import numpy as np

# Create a large NumPy array
numpy_array = np.random.rand(1000000)

# Calculate statistical measures
mean = np.mean(numpy_array)
std_dev = np.std(numpy_array)

print(f"Mean: {mean}, Standard Deviation: {std_dev}")


Mean: 0.49997691719002174, Standard Deviation: 0.28875672136149166


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output

-->np.vstack() vs np.hstack() in NumPy
np.vstack()
Purpose: Vertically stacks arrays (row-wise).

Usage: np.vstack((array1, array2, ...))

In [ ]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
vstacked_array = np.vstack((array1, array2))

print(vstacked_array)


np.hstack()
Purpose: Horizontally stacks arrays (column-wise).

Usage: np.hstack((array1, array2, ...))


In [ ]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
hstacked_array = np.hstack((array1, array2))

print(hstacked_array)


np.vstack(): Combines arrays vertically.

np.hstack(): Combines arrays horizontally.

Both functions are useful for different stacking operations in NumPy

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions

-->np.fliplr() vs np.flipud() in NumPy
np.fliplr()
Purpose: Flips an array left to right (horizontally).

Usage: np.fliplr(array)

Effect: Reverses the order of columns in the array.

In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Apply np.fliplr to flip the array left to right
flipped_lr = np.fliplr(arr)

print("Original array:\n", arr)
print("Array after fliplr:\n", flipped_lr)


np.flipud()
Purpose: Flips an array upside down (vertically).

Usage: np.flipud(array)

Effect: Reverses the order of rows in the array.

Example:

In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Apply np.flipud to flip the array upside down
flipped_ud = np.flipud(arr)

print("Original array:\n", arr)
print("Array after flipud:\n", flipped_ud)


np.fliplr(): Flips an array horizontally (left to right), reversing the column order.

np.flipud(): Flips an array vertically (upside down), reversing the row order.

Both functions are useful for manipulating the orientation of arrays in NumPy.

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

-->Purpose: Splits an array into multiple sub-arrays.

Syntax: np.array_split(array, indices_or_sections, axis=0)

array: The input array to be split.

indices_or_sections: Number of splits (if integer) or specific indices (if list).

axis: The axis along which to split the array. Default is 0 (split along rows).

Handling Uneven Splits: Distributes the remaining elements as evenly as possible when the array can't be evenly divided.

np.array_split(): Splits arrays into smaller sub-arrays, handling uneven splits by distributing elements as evenly as possible.


In [ ]:
import numpy as np

# Create an array
arr = np.arange(10)

# Split the array into 3 parts
splits = np.array_split(arr, 3)

print("Splits:")
for i, split in enumerate(splits):
    print(f"Split {i}:", split)


10.. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

-->Vectorization and Broadcasting in NumPy
Vectorization:

Purpose: Perform element-wise operations on entire arrays without explicit loops.

Benefits:

Faster computations due to low-level optimizations.

Cleaner, more readable code.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
vectorized_result = arr * 2
print(vectorized_result)  # Output: [ 2  4  6  8 10]


Broadcasting:

Purpose: Perform operations on arrays of different shapes.

Benefits:

Enables arithmetic operations without the need for resizing arrays.

Efficient memory usage by avoiding unnecessary data duplication.

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
broadcast_result = arr1 + arr2
print(broadcast_result)
# Output:
# [[ 2  4  6]
#  [ 5  7  9]]


Contribution to Efficient Array Operations:

Speed: Both vectorization and broadcasting use optimized, low-level implementations for faster execution.

Memory: Efficiently handle large datasets without unnecessary memory usage.

Code Simplicity: Simplify code by eliminating explicit loops and complex reshaping.

These concepts make NumPy powerful for numerical and scientific computing, enhancing both performance and usability.

In [17]:
#1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
arr1=np.random.randint(1,101,(3,3))
arr1

array([[ 13,  11,  70],
       [ 75,  73,  98],
       [100,  92,  58]])

In [ ]:
np.roll(arr1,-1)#interchanging the row.

array([[24, 32, 59],
       [63, 73, 10],
       [34, 38, 65]])

In [ ]:
np.roll(arr1,3)#interchanging the column.

array([[10, 34, 38],
       [65, 24, 32],
       [59, 63, 73]])

In [ ]:
#2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [8]:
arr=np.ones(10,dtype=int)

In [ ]:
arr.reshape(2,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
arr.reshape(5,2)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
#3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
#In this example, the np.pad function adds a border of zeros around the original array.
#You can change the constant_values parameter to fill the border with a different element
arr1=np.random.rand(4,4)
arr1

array([[0.94248632, 0.91919128, 0.12317989, 0.43464522],
       [0.53301373, 0.33670515, 0.10324747, 0.95264219],
       [0.39066566, 0.31233474, 0.01086277, 0.83082586],
       [0.72642674, 0.76554327, 0.2589755 , 0.51180867]])

In [ ]:
padded_arr=np.pad(arr1, pad_width=1,mode='constant',constant_values=0)
padded_arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.94248632, 0.91919128, 0.12317989, 0.43464522,
        0.        ],
       [0.        , 0.53301373, 0.33670515, 0.10324747, 0.95264219,
        0.        ],
       [0.        , 0.39066566, 0.31233474, 0.01086277, 0.83082586,
        0.        ],
       [0.        , 0.72642674, 0.76554327, 0.2589755 , 0.51180867,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [ ]:
#4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

#CONCEPT==>np.arange(10, 65, 5) generates an array starting at 10 and ending before 65,
#with a step of 5.
#The end value is exclusive, so we use 65 to include 60 in the array.
arr=np.arange(10,65,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [ ]:
#5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
l= ['python', 'numpy', 'pandas']
np.array(l)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.upper(l)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
np.char.capitalize(l)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [ ]:
np.char.lower(l)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.title(l)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [ ]:
#6.Generate a NumPy array of words. Insert a space between each character of every word in the array.

#We use the np.char.join function to insert a space between each character of every word in the array.
#The np.char.join function takes two arguments: the separator (in this case, a space ' ') and the array of words.
l= ['python', 'numpy', 'pandas']
np.array(l)
spaced_words=np.char.join(' ',l)
spaced_words

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [ ]:
#7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
array1=[[1,2],[3,4]]
array2=[[5,6],[7,8]]
a=np.array(array1)
b=np.array(array2)

array([[5, 6],
       [7, 8]])

In [ ]:
a


array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
#element-wise addition
add=a+b
#element-wise subtraction
sub=a-b
#element-wise multiplication
multi=a*b
#element-wise division
div=a/b
print("Element-wise addition",add)
print("Element-wise addition",sub)
print("Element-wise addition",multi)
print("Element-wise addition",div)

Element-wise addition [[ 6  8]
 [10 12]]
Element-wise addition [[-4 -4]
 [-4 -4]]
Element-wise addition [[ 5 12]
 [21 32]]
Element-wise addition [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
#8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np
identity_matrix=np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
diagonal_elements=np.diagonal(identity_matrix)
diagonal_elements

array([1., 1., 1., 1., 1.])

In [ ]:
#another approach or by using extract function.
diagonal_elements=np.extract(np.eye(5,dtype=bool),identity_matrix)
diagonal_elements

array([1., 1., 1., 1., 1.])

In [ ]:
#9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, 100)

# Find and display all prime numbers in the array
prime_numbers = [num for num in arr if is_prime(num)]

print("Array of random integers:", arr)
print("Prime numbers in the array:", prime_numbers)


array([[ 58, 364, 885, 227],
       [294, 435, 711, 963],
       [424, 323, 114, 651],
       [504, 117,  64, 850],
       [914,  91, 674, 634],
       [955, 256, 785, 866],
       [184, 609,  96, 787],
       [731, 210, 233, 773],
       [504, 431, 994, 428],
       [912, 902, 559, 745],
       [836, 551, 641, 488],
       [770,  85, 129, 482],
       [353, 689, 135, 561],
       [212, 392, 659, 945],
       [945, 526, 971,  63],
       [  2, 833, 149, 291],
       [133, 974, 448, 493],
       [322, 173, 670, 656],
       [651, 633, 666, 715],
       [111, 122,  34, 508],
       [577, 449, 641, 575],
       [883, 953, 748, 770],
       [335, 858, 165, 179],
       [388, 464, 856, 106],
       [603, 781, 102, 554]])

In [ ]:
#10Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages
temperature=np.random.randint(1,51,(3,10))
temperature

array([[20, 36, 17, 25, 28, 30, 44, 37, 11, 41],
       [14,  2,  8,  8, 15, 30, 16, 43, 20, 38],
       [ 5, 50, 30,  6,  2, 27, 14,  3, 41, 39]])

In [ ]:
temperature.mean()

23.333333333333332